# ─────────────────────────────────────────────────────────────────────────────
# MySQL — payment-billing-service
# Banco: payment_db
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pay-pvc
  namespace: fiap-oficina
  labels:
    app: mysql-payment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-payment
  namespace: fiap-oficina
  labels:
    app: mysql-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-payment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-payment
    spec:
      containers:
        - name: mysql-payment
          image: mysql:8.2
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "payment_db"
            - name: MYSQL_USER
              value: "oficina_user"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: MYSQL_PAY_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-pay-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -p$(MYSQL_ROOT_PASSWORD)
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -p$(MYSQL_ROOT_PASSWORD)
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: mysql-pay-storage
          persistentVolumeClaim:
            claimName: mysql-pay-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-payment
  namespace: fiap-oficina
  labels:
    app: mysql-payment
spec:
  type: ClusterIP
  selector:
    app: mysql-payment
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
