apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: fiap-oficina
  labels:
    app: tech-challenge-fase3
type: Opaque
stringData:
  MYSQL_SO_PASSWORD: "oficina_pass"
  MYSQL_PAY_PASSWORD: "oficina_pass"
  RABBITMQ_DEFAULT_PASS: "guest"
  MERCADO_PAGO_ACCESS_TOKEN: "TEST-TOKEN"
  RESEND_API_KEY: "re_placeholder"