apiVersion: v1
kind: Service
metadata:
  name: service-order-service
  namespace: fiap-oficina
  labels:
    app: service-order-service
spec:
  type: ClusterIP
  selector:
    app: service-order-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: payment-billing-service
  namespace: fiap-oficina
  labels:
    app: payment-billing-service
spec:
  type: ClusterIP
  selector:
    app: payment-billing-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-ingress
  namespace: fiap-oficina
  labels:
    app: oficina-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.oficina.com
      secretName: oficina-tls
  rules:
    - host: api.oficina.com
      http:
        paths:
          # ── service-order-service (porta 8080) ─────────────────────────
          - path: /api/service-orders
            pathType: Prefix
            backend:
              service:
                name: service-order-service
                port:
                  number: 80
          - path: /api/quotations
            pathType: Prefix
            backend:
              service:
                name: service-order-service
                port:
                  number: 80

          # ── payment-billing-service (porta 8081) ───────────────────────
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: payment-billing-service
                port:
                  number: 80
